import { ProjectCard } from "@/components/project-card"
import { Card } from "@/components/ui/card"
import { GradientHeading } from "@/components/gradient-heading"

export default function BlogCategoriesPage() {
  const categories = [
    {
      title: "Auto-Generated Blog Posts",
      description: "Explore blog posts automatically generated by our AI for various topics.",
      status: "Active",
      lastUpdated: "2025-06-21",
      slug: "auto-generated",
    },
    {
      title: "SEO Content",
      description: "Dive into AI-optimized content designed to boost search engine rankings.",
      status: "Active",
      lastUpdated: "2025-06-15",
      slug: "seo-content",
    },
    {
      title: "Social Media Posts",
      description: "Browse AI-crafted posts ready for various social media platforms.",
      status: "Active",
      lastUpdated: "2025-06-18",
      slug: "social-media",
    },
    {
      title: "AI Agent Responses",
      description: "Review curated responses and insights from our AI agents.",
      status: "Active",
      lastUpdated: "2025-06-20",
      slug: "agent-responses",
    },
  ]

  return (
    <main className="flex min-h-screen flex-col items-center p-8 bg-background text-foreground">
      <div className="container max-w-4xl mx-auto px-4 py-12">
        <GradientHeading text="Writing Repository" className="mb-12" />
        <Card className="jupiter-panel p-6 rounded-xl">
          <h2 className="subheading-large text-center mb-8 text-primary">Posts</h2>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {categories.map((category) => (
              <ProjectCard
                key={category.slug}
                title={category.title}
                description={category.description}
                status={category.status}
                lastUpdated={category.lastUpdated}
                className="hover:scale-[1.02] transition-transform duration-200 ease-in-out"
              />
            ))}
          </div>
        </Card>
      </div>
    </main>
  )
}
